// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEYIa2eY-LErhSAaOWh1TrS5v0RFDHer8',
    appId: '1:161881117391:web:386079726a606302719dba',
    messagingSenderId: '161881117391',
    projectId: 'clientesflutter',
    authDomain: 'clientesflutter.firebaseapp.com',
    storageBucket: 'clientesflutter.firebasestorage.app',
    measurementId: 'G-FFTD1S88XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBesPnrw0BioF1r7JLYaWmiC8ovgannKGE',
    appId: '1:161881117391:android:442385c01d0a95ec719dba',
    messagingSenderId: '161881117391',
    projectId: 'clientesflutter',
    storageBucket: 'clientesflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbDqAwITbwBMLFA8PqgXYIA3udsUy3b7Q',
    appId: '1:161881117391:ios:c1dd22fb2576a638719dba',
    messagingSenderId: '161881117391',
    projectId: 'clientesflutter',
    storageBucket: 'clientesflutter.firebasestorage.app',
    iosBundleId: 'com.example.cadastroCliente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbDqAwITbwBMLFA8PqgXYIA3udsUy3b7Q',
    appId: '1:161881117391:ios:c1dd22fb2576a638719dba',
    messagingSenderId: '161881117391',
    projectId: 'clientesflutter',
    storageBucket: 'clientesflutter.firebasestorage.app',
    iosBundleId: 'com.example.cadastroCliente',
  );
}
